# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

org, repo = (ENV["GITHUB_REPOSITORY"]||"").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"]||"").split("/")



#platform :android do
#  desc "internal"
#  lane :internal do
#    upload_to_play_store(track: 'internal', release_status: 'draft', aab: "build/Android/Android.aab")
#  end
#end

#platform :ios do

    before_all do
        ENV["FASTLANE_USER"] = "ashley.tharp@gmail.com"
        #ENV["FASTLANE_PASSWORD"] = "qbzy-qltb-ncuu-hsti"
        ENV["FASTLANE_PASSWORD"] = "myGreenBeret2019"
    end

    lane :init_ci do
        setup_ci
        github_action(
            api_token: ENV["GH_PAT"],
            org: org,
            repo: repo,
            match_org: match_org,
            match_repo: match_repo,
            writable_deploy_key: true
        )
    end

    desc "sync codesigning certificates"
    lane :sync_certificates do
        app_store_connect_api_key(
            key_id: ENV["APPSTORE_KEY_ID"],
            issuer_id: ENV["APPSTORE_ISSUER_ID"],
            key_content: ENV['APPSTORE_P8']
        )

        match(
            type: "appstore",
            storage_mode: "git", 
            git_url: "https://github.com/sitting-duck/nothing-game-fastlane-certs.git",
            app_identifier: ENV["IOS_BUNDLE_ID"],
            git_basic_authorization: "c2l0dGluZy1kdWNrOmdocF8zYzE1VERRTFdmd01SZ3NjTnRvenhzbDM5cGVzSGsyYlZTZWQ="
        )
    end


    lane :beta do
    match
    set_ci if ENV['CI']
    match(type: 'appstore', readonly: 'true')
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
    end

#end

