# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "internal"
  lane :internal do
    upload_to_play_store(track: 'internal', release_status: 'draft', aab: "build/Android/Android.aab")
  end

end

platform :ios do

    lane :beta do
    cert(username: 'ashley.tharp@gmail.com')
    sigh(force: true, username: 'ashley.tharp@gmail.com', app_identifier: 'com.nothing.game.ios.gelwix')
    #upload_to_testflight(skip_waiting_for_build_processing: true)
    end

end
