name: nothing-game-deploy-ios
on: 
  push:
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true

    - name: cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-iOS
        restore-keys: |
         Library-

    - name: build
      uses: game-ci/unity-builder@v2.2.0
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} # temporary
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} # temporary
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }} #temporary
      with:
        targetPlatform: iOS
        versioning: Semantic
        buildName: iOS
        buildsPath: build
    - name: ListBuildDir
      run: ls -halp build
    - name: more print
      run: ls -halp build/iOS
    - name: more more print
      run: ls -halp build/iOS/iOS
    - name: find
      run: find . -name *.ipa


  upload_artifact:  
    name: upload-aftifact-for-actions-download-page
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: iOS
          path: build/iOS/iOS/

  fastlane:
    name: fastlane step
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle install
      - name: upload-fastlane-testflight
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'beta'
          verbose: true          
    #- name: Cleanup to avoid storage limit
    #  if: always()
    #  uses: geekyeggo/delete-artifact@v1
    #  with:
    #    name: Build-Android

